[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
